version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - revive
    - bodyclose
    - gocritic
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - ifElseChain
        - rangeValCopy
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true
        - name: unused-parameter
          disabled: true
    gosec:
      excludes:
        - G301
        - G304
        - G306

formatters:
  enable:
    - gofmt
    - goimports
