version: 2

project_name: replicate-images

builds:
  - main: ./cmd/replicate-images
    binary: replicate-images
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: kevinmichaelchen
      name: homebrew-tap
    homepage: https://github.com/kevinmichaelchen/replicate-images
    description: CLI for generating images from text prompts using Replicate
    license: MIT
    install: |
      bin.install "replicate-images"
    test: |
      system "#{bin}/replicate-images", "--help"
